-- THIS FILE ONLY CREATES THE DATABASE RUN 'run npm seed' AFTER RUNNING THIS TO GET SCHEMA AND TEST DATA

-- DROP DATABASE
DROP DATABASE IF EXISTS blog_db;

-- CREATE DATABASE
CREATE DATABASE blog_db;